DemoOuvidoria/DemoOuvidoria/Controllers/ListController.cs
using DemoOuvidoria.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoOuvidoria.Controllers
{
    public class ListController : Controller
    {
        // GET: List
        public ActionResult Index()
        {
            //Conexão com o Banco
            DemoOuvidoriaEntities db = new DemoOuvidoriaEntities();

            //Select na tabela Mensagem setando a uma Lista do tipo Mensagem (trazendo da tabela Mensagem do banco)
            List<Mensagem> mensagemLista = db.Mensagem.ToList();

            //Instancêando um Objeto MensagemEntidade 
            MensagemEntidade mensagemCompleta = new MensagemEntidade();

            //Criando uma Lista do tipo MensagemEntidade e recebendo a Lista setada anteriormente trazida do banco
            List<MensagemEntidade> mensagemcompletaLista = mensagemLista.Select(x => new MensagemEntidade
            {
                NomeColaborador = x.NomeColaborador,
                MensagemID = x.MensagemID,
                TelefoneColaborador = x.TelefoneColaborador,
                EmailColaborador = x.EmailColaborador,
                MensagemColaborador = x.MensagemColaborador,
                TipoMsgID = x.TipoMsgID,
                TipoMsgNome = x.TipoMensagem.TipoMsgNome
            }).ToList();

            return View(mensagemcompletaLista);

        }
    }
}

DemoOuvidoria/DemoOuvidoria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="http://www.mcmmontagens.com.br/wp-content/themes/mcm/assets/img/misc/MCM-montagens-industriais.png">
                @Html.ActionLink("Registrar Mensagem", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Visualizar Registros", "Index", "List", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer class="estilomcm">
            <p>&copy; - @DateTime.Now.Year  MCM Montagens Industriais</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>